# https://medium.com/google-cloud/continuous-delivery-in-a-microservice-infrastructure-with-google-container-engine-docker-and-fb9772e81da7

language: python
python:
    - "3.7"

# Cache Gcloud SDK between commands
cache:
  directories:
    - "$HOME/google-cloud-sdk/"

services:
  - docker

env:
  global:
    - GOOGLE_APPLICATION_CREDENTIALS=~/gcloud-service-key.json
    - PROJECT_NAME_STG=dixneuf19-gke
    - CLUSTER_NAME_STG=your-first-cluster-1
    - PROJECT_NAME_PRD=dixneuf19-gke
    - CLUSTER_NAME_PRD=your-first-cluster-1
    - CLOUDSDK_COMPUTE_ZONE=europe-west1-d
    - DOCKER_IMAGE_NAME=dank-face-bot
    - KUBE_DEPLOYMENT_NAME=dank-face-bot
    - KUBE_DEPLOYMENT_CONTAINER_NAME=dank-face-bot

# safelist
branches:
  only:
  - master
  - /^deploy-.*$/
  - service

# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest


before_deploy:
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud --quiet version
  - gcloud --quiet components update
  - gcloud --quiet components beta update
  - gcloud --quiet components update kubectl

deploy:
  - provider: script
    script: ./deploy.sh
    skip_cleanup: true