version: '3'
services:
  dank-face-bot:
    build: .
    depends_on: 
      - insult-jmk
      - fuzzy-octo-disco
    image: dixneuf19/dank-face-bot
    environment:
      TOKEN: "${TOKEN}"
      INSULT_JMK_HOST: "insult-jmk"
      FIND_FACES_HOST: "fuzzy-octo-disco"
      DEFAULT_TIMEOUT: "${DEFAULT_TIMEOUT}"
    volumes:
      - pictures:/tmp

  insult-jmk:
    build: ../insult-jmk/.
    image: dixneuf19/insult-jmk
    
  fuzzy-octo-disco:
    build: ../fuzzy-octo-disco/.
    image: dixneuf19/find-faces
    environment:
      FACE_CROP_MARGIN: "-0.075"
    volumes:
      - pictures:/tmp
volumes:
  pictures: