apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${KUBE_DEPLOYMENT_NAME}-deployment
  labels:
    app: ${KUBE_DEPLOYMENT_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${KUBE_DEPLOYMENT_NAME}
  template:
    metadata:
      labels:
        app: ${KUBE_DEPLOYMENT_NAME}
    spec:
      containers:
      - name: $KUBE_DEPLOYMENT_NAME
        image: gcr.io/${PROJECT_NAME}/${DOCKER_IMAGE_NAME}:${TRAVIS_COMMIT}
        env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: telegram-token
                  key: token
            - name: INSULT_JMK_HOST
              value: insult-jmk-service
            - name: FIND_FACES_HOST
              value: find-faces-service
        volumeMounts:
          # name must match the volume name below
          - name: my-pvc-nfs
            mountPath: "/mnt"
      volumes:
      - name: my-pvc-nfs
        persistentVolumeClaim:
          claimName: nfs

